SET ECHO ON

CREATE TABLE PERSONAS (
    idPer VARCHAR(100) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    sexo CHAR(1)
);

CREATE TABLE OBRAS (
    idObra VARCHAR(100) PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    genero VARCHAR(100),
    AgnoEstreno NUMBER(4)
);

CREATE TABLE ACTORES (
    obraAct VARCHAR(100),
    actor VARCHAR(100),
    personaje VARCHAR(50),
    FOREIGN KEY(obraAct) REFERENCES OBRAS(idObra) ON DELETE CASCADE,
    FOREIGN KEY(actor) REFERENCES PERSONAS(idPer) ON DELETE CASCADE,
    CONSTRAINT ACTORES_PK PRIMARY KEY(obraAct, actor)
);

CREATE TABLE DIRECTORES (
    obraDir VARCHAR(100),
    director VARCHAR(100),
    FOREIGN KEY(obraDir) REFERENCES OBRAS(idObra) ON DELETE CASCADE,
    FOREIGN KEY(director) REFERENCES PERSONAS(idPer) ON DELETE CASCADE,
    CONSTRAINT DIRECTORES_PK PRIMARY KEY(obraDir, director)
);

CREATE TABLE STAFF (
    obraStaff VARCHAR(100),
    staff VARCHAR(100),
    funcion VARCHAR(100),
    FOREIGN KEY(obraStaff) REFERENCES OBRAS(idObra) ON DELETE CASCADE,
    FOREIGN KEY(staff) REFERENCES PERSONAS(idPer) ON DELETE CASCADE,
    CONSTRAINT STAFF_PK PRIMARY KEY(obraStaff, staff, funcion)
);

CREATE TABLE GENERO (
    nomGen VARCHAR(100),
    obraGen VARCHAR(100),
    FOREIGN KEY(obraGen) REFERENCES OBRAS(idObra) ON DELETE CASCADE,
    CONSTRAINT GENERO_PK PRIMARY KEY(nomGen,ObraGen)
);

CREATE TABLE EPISODIOS (
    obraEp VARCHAR(100) PRIMARY KEY,
    num NUMBER(4),
    temp NUMBER(4),
    FOREIGN KEY(obraEp) REFERENCES OBRAS(idObra) ON DELETE CASCADE
);

CREATE TABLE SERIES (
    obraSer VARCHAR(100) PRIMARY KEY,
    inicio NUMBER(4),
    fin NUMBER(4),
    FOREIGN KEY(obraSer) REFERENCES OBRAS(idObra) ON DELETE CASCADE,
    CHECK (inicio < fin)
);

CREATE TABLE PELICULAS (
    peli VARCHAR(100) PRIMARY KEY,
    peli2 VARCHAR(100),
    tipo VARCHAR(20),
    FOREIGN KEY(peli) REFERENCES OBRAS(idObra) ON DELETE CASCADE,
    FOREIGN KEY(peli2) REFERENCES PELICULAS(peli) ON DELETE CASCADE
);